apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: electronic1904.azurecr.io/biradarajaydjangonotesapp:$(Build.BuildId)
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: django-notes-service
spec:
  type: LoadBalancer
  selector:
    app: django
  ports:
    - port: 80
      targetPort: 8000
