apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-notes-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: django-notes
  template:
    metadata:
      labels:
        app: django-notes
    spec:
      containers:
      - name: django-notes
        image: electronic1904.azurecr.io/biradarajaydjangonotesapp:$(Build.BuildId)
        ports:
        - containerPort: 8000
